### ISSUE TITLE
Can protocols override methods or define constructors?

### ISSUE THREAD

**Issue by justinfagnani** [michaelficarra/ecmascript-interfaces-proposal#10]
I currently use mixins heavily, but rely on their ability to override methods, define constructors and make super calls.

It seems like in the current form I wouldn't be able to use protocols at all. Is this something that could be added?

**Comment by michaelficarra** [comment]
Symbol-named methods can be overwritten just fine. I'm not sure what you mean about defining constructors. I'll add a note to the README that super calls are an open question, but I'm going to guess that they wouldn't work because the functions will have an undefined `[[HomeObject]]` slot.
