### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by freddi301** [michaelficarra/ecmascript-interfaces-proposal#11]
Interfaces with default methods (like in java 8) essentially are the same as traits.
I can't see how protocols can be that useful without signatures and at least a type system.
The syntax using `object[Protocol.symbol]` is very good for encapsulation, but too verbose.

**Comment by gabejohnson** [comment]
> Interfaces with default methods (like in java 8) essentially are the same as traits.

Okay

> I can't see how protocols can be that useful without signatures and at least a type system.

So the `Promise` and `Iterator` protocols aren't useful? Also, this proposal has runtime checks: `B implements A`.

> The syntax using object[Protocol.symbol] is very good for encapsulation, but too verbose.

```js
const { symbol } = Protocol;
object[symbol];
```

See https://github.com/gabejohnson/fantasy-interfaces for some examples.

**Comment by michaelficarra** [comment]
@freddi301 See [my proposal slides](https://docs.google.com/presentation/d/1WrvSyslnF-5VnPj3k3HRq8MRzuiSN1kQ6ENE1iUSmDU/edit?usp=sharing) for some example calling patterns which might be more comfortable for you.

**Comment by freddi301** [comment]
@gabejohnson 
> So the Promise and Iterator protocols aren't useful? Also, this proposal has runtime checks: B implements A.

Of course they are, but they are well known. The strength of protocols/interfaces are their signatures, in a large project, like a tipical java enterprise monsters, you program always against interfaces. So "oh to implement this interface you have to declare X and Y" but nobody tells you what X and Y are. Maybe with Typescript/Flow annotation it could make sense to me.

> `const { symbol } = Protocol;
object[symbol];`

fair, with low number of protocols and name collisions it will be fine

@michaelficarra 
slide 12 looks nice

As is now, how it is different to just use an exported symbol to assign an object (containing implementation of the protocol) to a prototype?

**Comment by michaelficarra** [comment]
@freddi301 It's not much different than that. It also checks for the necessary implementation and takes care of complicated interface hierarchies. But this pattern is very cumbersome without some supporting syntax. See the sample output in the [sweet-interfaces README](https://github.com/disnet/sweet-interfaces) for what it would look like doing this yourself. For the same reasons, we have the `class` syntax.

**Comment by freddi301** [comment]
@michaelficarra ok, sintactic sugar is enough, i'm conviced.
