### ISSUE TITLE
Make `implements` a binary operator when in expression position

### ISSUE THREAD

**Issue by gabejohnson** [michaelficarra/ecmascript-interfaces-proposal#5]
To address https://github.com/michaelficarra/ecmascript-interfaces-proposal/issues/3#issuecomment-308933421 `implements` could double as a binary operator when in expression position.
`(implements) :: Function -> Protocol -> Boolean`
```js
protocol A {
  a() { ... }
}
protocol B {
  b() { ... }
}

class C implements A {}; // statement
class D implements B {}; // statement
Array implements A; // statement
Array implements B; // statement

C implements A && // expression
D implements B && // expression
!(C implements B || D implements A) && // expression
Array implements A && Array implements B; // expression
```

**Comment by michaelficarra** [comment]
I think making this distinction would be very confusing, considering we have ExpressionStatement for using Expressions in Statement position and the only current restrictions on it are in the leading tokens. I will just change the operator to be querying as suggested in #3 and add a Reflect API for mutating.

**Comment by gabejohnson** [comment]
Fair enough. I was thinking of `FunctionDeclaration` vs `FunctionExpression`. But then you'd probably have to do `(C implements A)` anyway. And that's still confusing.
