### ISSUE TITLE
Extending builtin collisions still exist

### ISSUE THREAD

**Issue by bmeck** [michaelficarra/ecmascript-interfaces-proposal#6]
It seems the methods of interfaces are placed in the string namespace. This continues the problems of extending builtins. See example:

```js
interface Length {
  sizer;
  length() {
      return this[sizer]();
  }
}
Array.prototype[Length.sizer] = function () {return this.length;};
Array implements Sizeof;
console.log([].length); // does this come from Length.length, or Array.prototype.length ?

interface Vector {
  lengther;
  directioner;
  length() { return this[lengther](); }
  direction() { return this[directioner](); }
}

Array.prototype[Vector.lengther] = function () {return this.length;};
Array.prototype[Vector.directioner] = function () {return 0;};
Array implements Vector;
console.log([].length); // does this come from Vector.length, Length.length, or Array.prototype.length ?
```

Might want to think of some way to specify which interface you are using the method from.

**Comment by michaelficarra** [comment]
@bmeck Agreed. I called this out in the [open questions section](https://github.com/michaelficarra/ecmascript-interfaces-proposal#open-questions-or-issues). I've decided to change the proposal so that the methods are also symbol-named, but haven't yet update it. I'll leave this open until I make the change.

**Comment by Jamesernator** [comment]
Symbol based methods do hit ergonomics a bit if it's a high-use feature, e.g. something like `Monad.bind` I'd expect to be using very frequently which would  get tedious fast using `someMonad[Monad.bind](x => x.toUpperCase())`.

It's perhaps a bit bad but when I've done interface-esque things in the past I've generally used them with the `::` plugin in Babel (I know Stage-0 plugins are bad but I find the ergonomics worthwhile enough to potentially be locked to a specific plugin) e.g.

```js
const matchSymbol = Symbol('match')

function match(...args) {
    return this[matchSymbol](...args)
}

// To what extent this is abuse of the spec I dunno
equals[Symbol.toPrimitive] = _ => equalsSymbol

class Point {
    constructor(x, y) {
        this.x = x
        this.y = y
    }

    [equals](other) {
        return this.x === other.x && this.y === other.y
    }
}

const point1 = new Point(10, 20)
const point2 = new Point(10, 20)

point1::match(point2) // true
```

Without depending on `::` happening anytime soon I wonder if there's a way to make it really nice ergonomically but also still without the string collision issue.

**Comment by michaelficarra** [comment]
@Jamesernator I, too, was worried about the ergonomics, but the string namespace collisions are just too much of a deal breaker to ignore. Using a local name like

```js
let bind = Monad.bind;
someMonad[bind](_ => _)
```

is not so bad, and I intend to describe the interactions with the bind operator in [its section in the README](https://github.com/michaelficarra/ecmascript-interfaces-proposal#ecmascript-proposed-bind--operator).

I'm happy to see so much interest. I'm going to get to these updates as soon as I can.

**Comment by gabejohnson** [comment]
@michaelficarra your change simply reflects what was already implemented in https://github.com/disnet/sweet-interfaces. Correct?

**Comment by michaelficarra** [comment]
@gabejohnson No, I believe I'll need to make changes to the implementation to reflect the last couple commits. Still have yet to rename `interface` to `protocol`. I think that's the last change I had planned but had not gotten around to. Is there anything else I've missed?

**Comment by ljharb** [comment]
O.o why "protocol" over "interface"?

**Comment by michaelficarra** [comment]
@ljharb A request from the TypeScript team to avoid conflict. I like both just fine. See #3.
