### ISSUE TITLE
Is `export interface` needed?

### ISSUE THREAD

**Issue by bmeck** [michaelficarra/ecmascript-interfaces-proposal#7]
It seems that interfaces are objects, so couldn't you just:

```js
interface Monad {/*...*/};
export default Monad;
```

**Comment by michaelficarra** [comment]
It's just as necessary as any of the other combined declaration/export forms. You could make the same argument that we don't need

```js
export class C {}
```

because we have

```js
class C {}
export { C }
```

or

```js
export function f() {}
```

because we have

```js
function f() {}
export { f }
```

For consistency, I will leave this in the proposal.

**Comment by bmeck** [comment]
Ah, might want to clear that up then, I assumed it was w/o a body.

**Comment by bmeck** [comment]
like:

```
export interface T;
```

**Comment by michaelficarra** [comment]
Okay, I will clear that up. Thanks for the feedback.
