### ISSUE TITLE
Reflect.implement should throw if its first argument is not constructible

### ISSUE THREAD

**Issue by bakkot** [michaelficarra/ecmascript-interfaces-proposal#8]

**Comment by ljharb** [comment]
Would this be done with `IsConstructor`, or by actually constructing it?

**Comment by bakkot** [comment]
I would expect `IsConstructor`, certainly. Invoking it can have side effects; this should be exactly the same check done by the `extends` clause of a class literal.

**Comment by ljharb** [comment]
@michaelficarra did you mean to close this issue with that commit?

**Comment by michaelficarra** [comment]
@ljharb Yeah. There's no spec text for this proposal yet, so the only action item here was to update the implementation. When I write spec text, I'll have to make sure it is specified this way. But I just realised I forgot to add a test (the most important part!) so I'll go do that now.
